title: English 2010 Portfolio
description: My English 2010 Portfolio - By Landon Conover
theme: jekyll-theme-cayman
--baseurl: /English2010
# Dependencies
markdown:    kramdown
highlighter: pygments
collections:
  papers:
    output: true
  ReadingResponses:
    output: true
