title: English 2010 Portfolio
description: My English 2010 Portfolio - By Landon Conover
remote_theme: mmistakes/minimal-mistakes@4.15.1
--baseurl: /English2010
# Dependencies
markdown:    kramdown
highlighter: pygments
collections:
  papers:
    output: true
  ReadingResponses:
    output: true
